name: MERN CI/CD Pipeline

on:
  push:
    branches:
      - main      #triggers on pushes to the main branch
  pull_request:
    branches:
      - main      #triggers on pull request to the main branch

jobs:
  build-the-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          # cache: 'npm'

      - name: Install dependencies for frontend
        working-directory: ./frontend
        run: npm ci

      - name: Build-frontend
        working-directory: ./frontend
        run: npm run build
  
  validate-the-backend:
    needs: build-the-frontend              # frontend needs to be built before validating backend
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      MONGO_URI: ${{ secrets.MONGO_URI }}
      PORT: ${{ secrets.PORT }}
      CLIENT_URL: ${{ secrets.CLIENT_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          # cache: 'npm'

      - name: Install dependencies for the backend
        working-directory: ./backend
        run: npm ci

      - name: Validate-backend-start
        working-directory: ./backend
        run: node -c index.js         # checks for syntax errors without executing the code
      
    
